version: '2'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
        - "80:80"
    volumes:
        - ./conf.d:/etc/nginx/conf.d     
networks:
  default:
    external:
      name: nginx_node         