---
- hosts: node_app
  become: yes
  tasks:  
    - docker_service:
        project_name: hooq
        definition:
          version: '1'
          services:
            ecommerce:
              container_name: node_app
              image: S3:/xxxxx/node_app:v1.0.0
              command: pm2 start app.js --no-daemon --watch -i max --max-memory-restart 3G --merge-logs --log-date-format="YYYY-MM-DD HH:mm Z"
              volumes:
                 - /var/jenkins/workspace/hooq_node_app:/app
              restart: unless-stopped
              ports:
                 - "3333:3333"